### ISSUE TITLE
ERROR: (gcloud.app.deploy) Error Response: [9]  [INFO] GCLOUD: Application startup error:

### ISSUE THREAD

**Issue by buckyballs** [GoogleCloudPlatform/app-maven-plugin#137]
I am trying to deploy spring-boot project on gcloud, project get deployed successfully in gcloud local environment and working as expected. Global deployment using "mvn appengine:deploy" fails with error,
```
[INFO] GCLOUD: cfe0fd451832: Mounted from google-appengine/nodejs
[INFO] GCLOUD: d2bb1f68461f: Pushed
[INFO] GCLOUD: latest: digest: sha256:3920f1dd733c7ce2a81226143644168b35f4abb729df0ed4b1930e66a5e01423 size: 6965
[INFO] GCLOUD: DONE
[INFO] GCLOUD: -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------
[INFO] GCLOUD: 
[INFO] GCLOUD: Updating service [default]...
[INFO] GCLOUD: ...................................................................................................................................................................................
........................................................................................................................failed.
[INFO] GCLOUD: ERROR: (gcloud.app.deploy) Error Response: [9] 
[INFO] GCLOUD: Application startup error:
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/classes/httpErrorCodes.properties  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/classes/xmlconfig.xml  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/classes/templates/index.html  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/classes/templates/participant/winner.html  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/classes/templates/participant/participantform.html  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/classes/templates/participant/show.html  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/classes/templates/email/lotteryWinnerEmail.vm  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/classes/templates/error.html  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/classes/templates/lottery/show.html  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/classes/templates/lottery/lotteryform.html    
```

I am using spring-boot 1.3.0.RELEASE and java 8. Looks like jettey server is looking for particular folder structure to deploy spring boot app successfully. Any idea to fix this issue ?

app.yaml:
```yaml
runtime: java
env: flex
runtime_config:  # Optional
  jdk: openjdk8
handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always  # Require HTTPS
manual_scaling:
  instances: 1
```
Thanks
Ishtiaq

**Comment by patflynn** [comment]
@ishtiaqmaqsood I'm noticing you have a WEB-INF directory.   Is your spring boot project configured to be packaged as a WAR?  If so you need to use the jetty 9 app engine flex runtime. 

```
runtime_config:  # Optional
  jdk: openjdk8
 server: jetty9


```
the pure open jdk8 runtime will only work with jar based springboot apps.

Could you include the config parameters you're using in the app-maven-plugin?

**Comment by ishtiaqmaqsood** [comment]
Thanks for the reply. Yes my spring boot project is configured to be packaged as war. I added server: jetty9 in aap.yaml as you mentioned. 
Here is my pom.xml plugins section, would you please guide on "include the config parameters you're using in the app-maven-plugin, where to add this config parameter? do I need to have jetty plugin in my pom for this which I don't have in my pom at this time?" 

...
    <build>
        <plugins>

            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.6.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>appengine-maven-plugin</artifactId>
                <version>1.0.0</version>
            </plugin>

        </plugins>
    </build>
...

**Comment by patflynn** [comment]
are you able to deploy now that you've modified the runtime?

**Comment by ishtiaqmaqsood** [comment]
No. It failed again with same error mentioned in the issue.

**Comment by meltsufin** [comment]
@ishtiaqmaqsood, in your original message, did you omit the end of the command output after it failed? To me, it seems that the app is failing on startup. Do you see any exceptions in the command output that you might've omitted? You can also try looking at the server logs in the Cloud Console for more hints on why it's crashing. Finally, it might be failing on startup due to insufficient memory.

Try adding this to your app.yaml:
```
resources:
  memory_gb: 2.0
```

**Comment by ishtiaqmaqsood** [comment]
Well, I am able to deploy my app to appengine but app behavior is not consistent as it was in local deployment mode. Same end points sometime works and sometime gives this error,
"Error: Server Error
The server encountered a temporary error and could not complete your request.
Please try again in 30 seconds."

Checking stackdriver logs I see below log repetitively showing up, I am not sure whether my app is not working consistently because of this log need to fix or it is something else I need to fix, I do not see this log in my local and app works consistently in local mode.

... 42 common frames omitted

2017-02-21 19:17:18.307 ERROR 1 --- [nio-8080-exec-7] o.a.c.c.C.[Tomcat].[localhost]           : Exception Processing ErrorPage[errorCode=0, location=/error]
 org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:393) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:426) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:342) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:317) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:110) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
at com.fasterxml.jackson.core.json.UTF8JsonGenerator.flush(UTF8JsonGenerator.java:1022) ~[jackson-core-2.6.3.jar!/:2.6.3]
at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:891) ~[jackson-databind-2.6.3.jar!/:2.6.3]
at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:264) ~[spring-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
at org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:100) ~[spring-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:222) ~[spring-webmvc-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:186) ~[spring-webmvc-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:80) ~[spring-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:126) ~[spring-webmvc-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814) ~[spring-webmvc-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737) ~[spring-webmvc-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) ~[spring-webmvc-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:720) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:468) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:439) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:305) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:182) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
 Caused by: java.io.IOException: Broken pipe
at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_121]
at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[na:1.8.0_121]
at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_121]
at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_121]
at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[na:1.8.0_121]
at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:124) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:172) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.coyote.http11.InternalNioOutputBuffer.writeToSocket(InternalNioOutputBuffer.java:139) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.coyote.http11.InternalNioOutputBuffer.addToBB(InternalNioOutputBuffer.java:197) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
at org.apache.coyote.http11.InternalNioOutputBuffer.access$000(InternalNioOutputBuffer.java:41) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.apache.coyote.http11.InternalNioOutputBuffer$SocketOutputBuffer.doWrite(InternalNioOutputBuffer.java:320) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.apache.coyote.http11.filters.ChunkedOutputFilter.doWrite(ChunkedOutputFilter.java:118) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.apache.coyote.http11.AbstractOutputBuffer.doWrite(AbstractOutputBuffer.java:256) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.apache.coyote.Response.doWrite(Response.java:501) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:388) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
 	... 42 common frames omitted

**Comment by patflynn** [comment]
@meltsufin should this be discussed in a runtimes bug?

**Comment by meltsufin** [comment]
@patflynn Yes, I think it belongs in this repo better: https://github.com/GoogleCloudPlatform/openjdk-runtime.
@ishtiaqmaqsood We'll need a sample app that reproduces this to diagnose further. Can you put it together?

**Comment by buckyballs** [comment]
@meltsufin here is sample application: https://github.com/buckyballs/lottery-app

**Comment by meltsufin** [comment]
@buckyballs Thanks for the sample app. I was able to reproduce, seeing that the app kept restarting but then finally came up. I think this is due to the app taking some time to start up and failing the health checks as it's starting up. As it's failing health checks, the flex agent decides to restart it. In any case, one thing you can do is disable heath checks in your app.yaml:
```yaml
health_check:
  enable_health_check: False
```
Alternatively, [tune the heath checking config](https://cloud.google.com/appengine/docs/flexible/java/configuring-your-app-with-app-yaml).

**Comment by buckyballs** [comment]
@meltsufin I am not able to deploy app and getting this error after disabling health check,
[INFO] GCLOUD: ERROR: (gcloud.app.deploy) Error Response: [13] Deployment Manager operation failed, name: operation-1490677589377-54bc36c307fe9-87b56ea4-18a362fd,
 error: [{"code":"RESOURCE_ERROR","location":"/deployments/aef-gclb/resources/aef-um","message":"{\"ResourceType\":\"compute.v1.urlMap\",\"ResourceErrorCode\":\"4
04\",\"ResourceErrorMessage\":{\"code\":404,\"errors\":[{\"domain\":\"global\",\"message\":\"The resource 'projects/lottery-app-158618/global/urlMaps/aef-um' was 
not found\",\"reason\":\"notFound\"}],\"message\":\"The resource 'projects/lottery-app-158618/global/urlMaps/aef-um' was not found\",\"statusMessage\":\"Not Found
\",\"requestPath\":\"https://www.googleapis.com/compute/v1/projects/lottery-app-158618/global/urlMaps/aef-um\"}}"}]

**Comment by patflynn** [comment]
+clouser who might know what's happening on the backend to cause this error.

**Comment by akerekes** [comment]
@clouser2

**Comment by akerekes** [comment]
@buckyballs Can you try to delete the broken version(s) though `console.cloud.google.com` and deploy a new version of the application without specifying the `version` element (i.e. let the deploy autogenerate a version number) while keeping the health checks disabled?

**Comment by elharo** [comment]
I just reproduced this in a different context:

```
Updating service [default]...failed.                                                               
ERROR: (gcloud.app.deploy) Error Response: [9] 
Application startup error:
Hello Docker
```

**Comment by buckyballs** [comment]
@akerekes I am getting this error, any idea to fix this,
[INFO] GCLOUD: ERROR: (gcloud.app.deploy) Error Response: [13] Deployment Manager operation failed, name: operation-1497378821260-551dbacbc42e0-a5ca1654-2ce110cf, error: [{"code":"RESOURCE_ERROR
","location":"/deployments/aef-gclb/resources/aef-um","message":"{\"ResourceType\":\"compute.v1.urlMap\",\"ResourceErrorCode\":\"404\",\"ResourceErrorMessage\":{\"code\":404,\"errors\":[{\"domai
n\":\"global\",\"message\":\"The resource 'projects/lottery-app-158618/global/urlMaps/aef-um' was not found\",\"reason\":\"notFound\"}],\"message\":\"The resource 'projects/lottery-app-158618/gl
obal/urlMaps/aef-um' was not found\",\"statusMessage\":\"Not Found\",\"requestPath\":\"https://www.googleapis.com/compute/v1/projects/lottery-app-158618/global/urlMaps/aef-um\"}}"}]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:33 min
[INFO] Finished at: 2017-06-13T13:33:52-05:00
[INFO] Final Memory: 20M/49M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:1.0.0:deploy (default-cli) on project lottery-app: Execution default-cli of goal com.google.cloud.tools:appengine-mav
en-plugin:1.0.0:deploy failed: Non zero exit: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by akerekes** [comment]
@loosebazooka

**Comment by patflynn** [comment]
@buckyballs we are looking into this.  Are you seeing the error consistently?

b/37478884

**Comment by chanseokoh** [comment]
Closing due to inactivity.
