### ISSUE TITLE
windows, path has " in it fails...

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/app-maven-plugin#199]
```
[INFO] --- appengine-maven-plugin:1.3.1:run (default-cli) @ helloworld_java8_GAE_standard ---
Jun 27, 2017 12:46:06 PM com.google.cloud.tools.appengine.cloudsdk.CloudSdk$Builder discoverSdkPath
SEVERE: com.google.cloud.tools.appengine.cloudsdk.PathResolver: exception thrown when searching for Google Cloud SDK
java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Users\DPE Admin\Downloads\apache-maven-3.5.0\bin"\gcloud
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at com.google.cloud.tools.appengine.cloudsdk.PathResolver.getLocationsFromPath(PathResolver.java:97)
        at com.google.cloud.tools.appengine.cloudsdk.PathResolver.getCloudSdkPath(PathResolver.java:47)
        at com.google.cloud.tools.appengine.cloudsdk.CloudSdk$Builder.discoverSdkPath(CloudSdk.java:719)
        at com.google.cloud.tools.appengine.cloudsdk.CloudSdk$Builder.build(CloudSdk.java:671)
        at com.google.cloud.tools.maven.CloudSdkAppEngineFactory.createDevServerForVersion(CloudSdkAppEngineFactory.java:74)
        at com.google.cloud.tools.maven.CloudSdkAppEngineFactory.devServerRunSync(CloudSdkAppEngineFactory.java:70)
        at com.google.cloud.tools.maven.RunMojo.runServer(RunMojo.java:286)
        at com.google.cloud.tools.maven.RunMojo.execute(RunMojo.java:282)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.480 s
[INFO] Finished at: 2017-06-27T12:46:06-07:00
[INFO] Final Memory: 26M/404M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:1.3.1:run (default-cli) on project helloworld_java8_GAE_standard: Execution default-cli of goal com.google.cloud.tools:appengine-maven-plugin:1.3.1:run failed: The Google Cloud SDK could not be found in the customary locations and no path was provided. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by loosebazooka** [comment]
Does your pom.xml have `"` in it?

**Comment by lesv** [comment]
Nope - that was coming from path which was set by a browse in Environment Variables in Windows.

My maven was / is in `c:\Users\DPE Admin\Downloads\apache-maven-3.5.-\bin` on a Windows 10 machine.

**Comment by loosebazooka** [comment]
Strange, but it looks like windows is okay with `"` in the path, anyway, I think this needs to be fixed in our core tools as it affects everything.

**Comment by lesv** [comment]
By default the browse command for setting a path adds it in.

**Comment by lesv** [comment]
Can't you use `where gcloud` windows and `which gcloud` mac/linux rather than parsing the path?

**Comment by loosebazooka** [comment]
I believe this was fixed in the latest sdk?

**Comment by TBuc** [comment]
There's a chance this is related to #229 .

**Comment by chanseokoh** [comment]
@TBuc I believe #229 is a different issue.
