### ISSUE TITLE
Unable to run local dev server - app wrongly identified as Flexible Environment application

### ISSUE THREAD

**Issue by deepfriedbrain** [GoogleCloudPlatform/app-maven-plugin#215]
I just converted my App Engine Java based project to a Maven project just so I could migrate from Cloud Endpoints Framework 1.0 to 2.0. After conversion to Maven, when I try to run the local dev server using the command `mvn -e appengine:run`, I get the following error.

```
[ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:1.3.1:run (default-cli) on project PMProc: Dev App Server does not support App Engine Flexible Environment applications. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:1.3.1:run (default-cli) on project PMProc: Dev App Server does not support App Engine Flexible Environment applications.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Dev App Server does not support App Engine Flexible Environment applications.
	at com.google.cloud.tools.maven.RunMojo.verifyAppEngineStandardApp(RunMojo.java:352)
	at com.google.cloud.tools.maven.RunMojo.execute(RunMojo.java:281)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

My plugin configuration is:

```
<plugin>
        <groupId>com.google.cloud.tools</groupId>
    	<artifactId>appengine-maven-plugin</artifactId>
    	<version>1.3.1</version>
    	<configuration>
	    <project>${endpoints.project.id}</project>
            <version>1</version>
       		<devserver.host>localhost</devserver.host>
       		<devserver.port>8888</devserver.port>
        </configuration>
</plugin>
```

My project is a standard app engine project. I'm not sure what causes the plugin to see it as a flexible environment project. I have the `appengine-web.xml` under WEB-INF folder.

Am I missing something? Any help would be appreciated. Thanks.

**Comment by loosebazooka** [comment]
Do you have an appengine-web.xml?

**Comment by deepfriedbrain** [comment]
I removed the plugin 'maven-war-plugin' and then it started to work. After adding it back, it still continues to work. I'm not sure whether that plugin is really needed. It's weird.

To answer your question, yes, I have the appengine-web.xml under my WEB-INF folder.

**Comment by loosebazooka** [comment]
Okay, yeah since this plugin supports both standard/flex environments, it has some logic to determine which you are targeting. It uses the appengine-web.xml for that, was there some special configuration on the maven-war-plugin?

**Comment by deepfriedbrain** [comment]
This is how it was configured as:

```
      <plugin>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.0.0</version>
        <configuration>
          <warSourceDirectory>war</warSourceDirectory>
        </configuration>
      </plugin>
```

**Comment by deepfriedbrain** [comment]
I changed the `war` to 'webapp` earlier today to conform to the Maven directory structure requirement. Maybe that's why it wasn't able to find the appengine-web.xml where it expected it to find. After removing the plugin, it started working, but why it continues to work after adding the plugin back is not clear to me.

**Comment by deepfriedbrain** [comment]
Thank you. The issue has been resolved. I appreciate the prompt and thorough responses.
