### ISSUE TITLE
_ah/admin/modules does not work with multi-service projects

### ISSUE THREAD

**Issue by the-rockkk** [GoogleCloudPlatform/app-maven-plugin#234]
I have a multi-service project I am trying to convert from the old Eclipse plugin to the Cloud tools plugin. 
 I seem to be able to run fine, however when navigating to _ah/admin/modules, I get a null pointer exception:
```
2017-12-12 08:43:15.384:WARN:oejs.ServletHandler:qtp1226020905-17: /_ah/admin/modules
java.lang.NullPointerException: null value in entry: version=null
	at com.google.appengine.repackaged.com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:34)
	at com.google.appengine.repackaged.com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:241)
	at com.google.apphosting.utils.servlet.ModulesServlet$1.apply(ModulesServlet.java:82)
	at com.google.apphosting.utils.servlet.ModulesServlet$1.apply(ModulesServlet.java:74)
	at com.google.appengine.repackaged.com.google.common.collect.Iterators$7.transform(Iterators.java:861)
	at com.google.appengine.repackaged.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.appengine.repackaged.com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:255)
	at com.google.appengine.repackaged.com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:214)
	at com.google.apphosting.utils.servlet.ModulesServlet.doGet(ModulesServlet.java:94)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:134)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.appengine.tools.development.jetty9.StaticFileFilter.doFilter(StaticFileFilter.java:123)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.appengine.tools.development.DevAppServerRequestLogFilter.doFilter(DevAppServerRequestLogFilter.java:44)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1751)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at com.google.appengine.tools.development.jetty9.DevAppEngineWebAppContext.doScope(DevAppEngineWebAppContext.java:94)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.appengine.tools.development.jetty9.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:597)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
```

This is painful since the services other that default get random ports, so without that admin page you have to check the log in each run to find the correct ports during debugging and testing.

To eliminate my project as the cause, I even tried create a simple test case with brand new project created using the Cloud Tools Plugin, with the same result:
```			<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>appengine-maven-plugin</artifactId>
				<version>${appengine.maven.plugin.version}</version>
				<configuration>
					<services>
						<!-- default service -->
						<service>${project.build.directory}/${project.build.finalName}</service>
						<!-- admin service -->
						<service>${project.basedir}/../JerseyTestAdmin/target/admin-service-${project.version}</service>
					</services>
				</configuration>
			</plugin>
```

**Comment by chanseokoh** [comment]
Internal bug ref: 36894893

**Comment by chanseokoh** [comment]
This probably has nothing to do with multi services. I believe you'll be able to reproduce this with a single service. If so, a workaround is to put the following into your `appengine-web.xml`.

```xml
<version>version-ignored-at-deploy-time-and-only-as-a-temporary-workaround</version>
```

You can actually put any value, but the value will be scrubbed off and not be used at deploy. I recommend you clearly document that the value will be ignored and used only to make the local dev server working.

**Comment by the-rockkk** [comment]
ok, I'll try that.  Ironically, I removed that entry because the validation issued a warning... :smile:

**Comment by chanseokoh** [comment]
> Ironically, I removed that entry because the validation issued a warning...

Yeah, we warn if `<version>` exists in `appengine-web.xml` for the reason that I explained earlier: it gets ignored at deploy. Unfortunately, this is the only workaround I can think of ATM. Hopefully the dev server fixes the issue eventually.

**Comment by the-rockkk** [comment]
The work around does work (adding a <version> element to appengine-web.xml). However it does have the annoyance of showing a warning, and I am one of the developers who believes you should remove all warnings from a project.... :)

**Comment by chrisjenx** [comment]
This is still an issue :(

**Comment by patflynn** [comment]
@chrisjenx 
We should have removed the version warning.  If you place the <version> element in the appengine-web.xml this issue should go away.
@loosebazooka

**Comment by chrisjenx** [comment]
Ok

**Comment by the-rockkk** [comment]
> We should have removed the version warning.
I'm using v1.9.64 of the appengine-maven-plugin and am still seeing this warning. I belive this is the latest version...
