### ISSUE TITLE
_ah/admin console fails to load when using dev appsever 2 (alpha)

### ISSUE THREAD

**Issue by eschultink** [GoogleCloudPlatform/app-maven-plugin#238]
### Background
Building with `mvn appengine:run`, from my `default` module. 

I have a multi-service java8 standard environment project.  I'm trying to upgrade to `2-alpha` version of the ~~plugin~~ dev appserver. I understand as "alpha", it's not expected to be reliable; but I thought you should be aware of the issue.

My plugin configuration looks as follows:
```xml
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>appengine-maven-plugin</artifactId>
                <version>${maven.appengine.plugin-version}</version>
                <configuration>
                    <project>${appengine.app.projectid}</project> <!-- TODO: seems to be ignored by dev server -->
                    <version>${module.version}</version>
                    <services>
                        <service>${targetDirectory}</service>
                        <!--for each service, reference it -->
                        <!-- TODO: interpolate these versions correctly from maven; they are NOT necessarily same as project.version -->
                        <service>${project.parent.basedir}/module-other/target/module-other-${project.version}</service>
                        <service>${project.parent.basedir}/module-another/target/module-another-${project.version}</service>
                    </services>
                    <!-- seems to run it with Python dev-server implementation; which also uses different local DB format -->
                    <devserver.version>2-alpha</devserver.version>
                    <devserver.storagePath>${project.basedir}/target/dev-env-state/</devserver.storagePath> <!-- only in 2-alpha  -->
                </configuration>
            </plugin>
```

### What Happens
Console output from war-plugin + appengine plugin, including dev server start-up:
```
[INFO] --- maven-war-plugin:2.4:exploded (war-exploded) @ module-frontend ---
[INFO] Exploding webapp
[INFO] Assembling webapp [module-frontend] in [/Users/erik/code/project/module-frontend/target/module-frontend-1.0-SNAPSHOT]
[INFO] Processing war project
[INFO] Copying webapp webResources [/Users/erik/code/project/module-frontend/src/main/webapp/WEB-INF] to [/Users/erik/code/project/module-frontend/target/module-frontend-1.0-SNAPSHOT]
[INFO] Copying webapp webResources [/Users/erik/code/project/module-frontend/src/main/resources] to [/Users/erik/code/project/module-frontend/target/module-frontend-1.0-SNAPSHOT]
[INFO] Copying webapp webResources [/Users/erik/code/project/module-frontend/target/generated/bundle-info] to [/Users/erik/code/project/module-frontend/target/module-frontend-1.0-SNAPSHOT]
[INFO] Copying webapp resources [/Users/erik/code/project/module-frontend/src/main/webapp]
[INFO] Webapp assembled in [1701 msecs]
[INFO] 
[INFO] <<< appengine-maven-plugin:1.3.2:run (default-cli) < package @ module-frontend <<<
[INFO] 
[INFO] --- appengine-maven-plugin:1.3.2:run (default-cli) @ module-frontend ---
Dec 18, 2017 11:30:46 AM com.google.cloud.tools.appengine.cloudsdk.CloudSdk logCommand
INFO: submitting command: /Users/erik/google-cloud-sdk/bin/dev_appserver.py /Users/erik/code/project/module-frontend/target/module-frontend-1.0-SNAPSHOT /Users/erik/code/project/module-other/target/module-other-1.0-SNAPSHOT /Users/erik/code/project/module-another/target/module-another-1.0-SNAPSHOT --storage_path=/Users/erik/code/project/module-frontend/target/dev-env-state
[INFO] GCLOUD: INFO     2017-12-18 19:30:54,461 devappserver2.py:105] Skipping SDK update check.
[INFO] GCLOUD: INFO     2017-12-18 19:30:54,565 api_server.py:301] Starting API server at: http://localhost:64662
[INFO] GCLOUD: INFO     2017-12-18 19:30:54,988 dispatcher.py:251] Starting module "default" running at: http://localhost:8080
[INFO] GCLOUD: INFO     2017-12-18 19:30:55,118 dispatcher.py:251] Starting module "other" running at: http://localhost:8081
[INFO] GCLOUD: INFO     2017-12-18 19:30:55,395 dispatcher.py:251] Starting module "another" running at: http://localhost:8082
[INFO] GCLOUD: INFO     2017-12-18 19:30:55,398 admin_server.py:116] Starting admin server at: http://localhost:8000
[INFO] GCLOUD: Dec 18, 2017 7:30:57 PM com.google.appengine.tools.development.SystemPropertiesManager setSystemProperties
[INFO] GCLOUD: INFO: Overwriting system property key 'java.util.logging.config.file', value '/Users/erik/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/config/sdk/logging.properties' with value 'WEB-INF/logging.properties' from '/Users/erik/code/project/module-other/target/module-other-1.0-SNAPSHOT/WEB-INF/appengine-web.xml'
[INFO] GCLOUD: Dec 18, 2017 7:30:57 PM com.google.appengine.tools.development.AbstractContainerService configure
[INFO] GCLOUD: WARNING: Null value for containerConfigProperties.get(devappserver.portMappingProvider)
[INFO] GCLOUD: 2017-12-18 19:30:57.593:INFO::main: Logging initialized @1230ms
[INFO] GCLOUD: 2017-12-18 19:30:58.209:INFO:oejs.Server:main: jetty-9.3.18.v20170406
[INFO] GCLOUD: 2017-12-18 19:30:59.384:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=23ms
[INFO] GCLOUD: Dec 18, 2017 7:31:05 PM org.reflections.Reflections scan
[INFO] GCLOUD: INFO: Reflections took 1853 ms to scan 5 urls, producing 319 keys and 2985 values 
[INFO] GCLOUD: 2017-12-18 19:31:06.765:INFO:oejsh.ContextHandler:main: Started c.g.a.t.d.j.DevAppEngineWebAppContext@385d819{/,file:///Users/erik/code/project/module-other/target/module-other-1.0-SNAPSHOT/,AVAILABLE}{/Users/erik/code/project/module-other/target/module-other-1.0-SNAPSHOT}
[INFO] GCLOUD: 2017-12-18 19:31:06.940:INFO:oejs.AbstractConnector:main: Started NetworkTrafficSelectChannelConnector@7af0affa{HTTP/1.1,[http/1.1]}{localhost:64693}
[INFO] GCLOUD: 2017-12-18 19:31:06.960:INFO:oejs.Server:main: Started @10597ms
[INFO] GCLOUD: Dec 18, 2017 7:31:06 PM com.google.appengine.tools.development.AbstractModule startup
[INFO] GCLOUD: INFO: Module instance other is running at http://localhost:64693/
[INFO] GCLOUD: Dec 18, 2017 7:31:06 PM com.google.appengine.tools.development.AbstractModule startup
[INFO] GCLOUD: INFO: The admin console is running at http://localhost:64693/_ah/admin
[INFO] GCLOUD: Dec 18, 2017 7:31:06 PM com.google.appengine.tools.development.devappserver2.DevAppServer2Impl doStart
[INFO] GCLOUD: INFO: Dev App Server is now running
[INFO] GCLOUD: Dec 18, 2017 7:30:57 PM com.google.appengine.tools.development.SystemPropertiesManager setSystemProperties
[INFO] GCLOUD: INFO: Overwriting system property key 'java.util.logging.config.file', value '/Users/erik/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/config/sdk/logging.properties' with value 'WEB-INF/logging.properties' from '/Users/erik/code/project/module-frontend/target/module-frontend-1.0-SNAPSHOT/WEB-INF/appengine-web.xml'
[INFO] GCLOUD: Dec 18, 2017 7:30:57 PM com.google.appengine.tools.development.AbstractContainerService configure
[INFO] GCLOUD: WARNING: Null value for containerConfigProperties.get(devappserver.portMappingProvider)
[INFO] GCLOUD: 2017-12-18 19:30:57.592:INFO::main: Logging initialized @1217ms
[INFO] GCLOUD: 2017-12-18 19:30:58.587:INFO:oejs.Server:main: jetty-9.3.18.v20170406
[INFO] GCLOUD: 2017-12-18 19:30:59.869:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=27ms
[INFO] GCLOUD: Dec 18, 2017 7:31:06 PM org.reflections.Reflections scan
[INFO] GCLOUD: INFO: Reflections took 1963 ms to scan 5 urls, producing 319 keys and 2985 values 
[INFO] GCLOUD: 2017-12-18 19:31:07.646:INFO:oejsh.ContextHandler:main: Started c.g.a.t.d.j.DevAppEngineWebAppContext@68af87ad{/,file:///Users/erik/code/project/module-frontend/target/module-frontend-1.0-SNAPSHOT/,AVAILABLE}{/Users/erik/code/project/module-frontend/target/module-frontend-1.0-SNAPSHOT}
[INFO] GCLOUD: 2017-12-18 19:31:07.694:INFO:oejs.AbstractConnector:main: Started NetworkTrafficSelectChannelConnector@6ee88e21{HTTP/1.1,[http/1.1]}{localhost:64692}
[INFO] GCLOUD: 2017-12-18 19:31:07.722:INFO:oejs.Server:main: Started @11330ms
[INFO] GCLOUD: Dec 18, 2017 7:31:07 PM com.google.appengine.tools.development.AbstractModule startup
[INFO] GCLOUD: INFO: Module instance default is running at http://localhost:64692/
[INFO] GCLOUD: Dec 18, 2017 7:31:07 PM com.google.appengine.tools.development.AbstractModule startup
[INFO] GCLOUD: INFO: The admin console is running at http://localhost:64692/_ah/admin
[INFO] GCLOUD: Dec 18, 2017 7:31:07 PM com.google.appengine.tools.development.devappserver2.DevAppServer2Impl doStart
[INFO] GCLOUD: INFO: Dev App Server is now running
[INFO] GCLOUD: Dec 18, 2017 7:31:12 PM com.google.appengine.tools.development.jetty9.LocalResourceFileServlet doGet
[INFO] GCLOUD: WARNING: No file found for: /_ah/warmup
[INFO] GCLOUD: INFO     2017-12-18 19:31:12,375 module.py:825] other: "GET /_ah/warmup HTTP/1.1" 404 83
```

After that, I attempt to follow the admin link: http://localhost:64692/_ah/admin

The request fails with a 500 error:
```
HTTP ERROR 500
Problem accessing /_ah/admin. Reason:

    Server Error
Caused by:
javax.servlet.ServletException: _ah_datastoreViewer@8b9526f0==com.google.apphosting.utils.servlet.DatastoreViewerServlet,jsp=null,order=-1,inst=false
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:664)
	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:499)
	at org.eclipse.jetty.servlet.ServletHolder.ensureInstance(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:776)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:579)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at com.google.appengine.tools.development.jetty9.DevAppEngineWebAppContext.doScope(DevAppEngineWebAppContext.java:94)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.appengine.tools.development.jetty9.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:597)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: com.google.appengine.tools.development.devappserver2.DevAppServer2Delegate cannot be cast to com.google.appengine.tools.development.ApiProxyLocal
	at com.google.apphosting.utils.servlet.DatastoreViewerServlet.init(DatastoreViewerServlet.java:124)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:643)
	... 28 more
Caused by:
java.lang.ClassCastException: com.google.appengine.tools.development.devappserver2.DevAppServer2Delegate cannot be cast to com.google.appengine.tools.development.ApiProxyLocal
	at com.google.apphosting.utils.servlet.DatastoreViewerServlet.init(DatastoreViewerServlet.java:124)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:643)
	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:499)
	at org.eclipse.jetty.servlet.ServletHolder.ensureInstance(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:776)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:579)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at com.google.appengine.tools.development.jetty9.DevAppEngineWebAppContext.doScope(DevAppEngineWebAppContext.java:94)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.appengine.tools.development.jetty9.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:597)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
```

The issue STILL happens, even if I omit my additional plugin configuration parameters: `storagePath`, `services` (making this effectively single-service project), etc. Eg, I still have the same problem even with the following minimal config:
```xml
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>appengine-maven-plugin</artifactId>
                <version>${maven.appengine.plugin-version}</version>
                <configuration>
                    <devserver.version>2-alpha</devserver.version>
                </configuration>
            </plugin>
```

**Comment by chanseokoh** [comment]
We recommend using dev appserver1 and not dev appserver2.

In any case, in your log, the admin console is at `http://localhost:8000` (no extra path). The log that it is at `http://localhost:6xxxx/_ah/admin` is wrong.

```
[INFO] GCLOUD: INFO     2017-12-18 19:30:55,398 admin_server.py:116] Starting admin server at: http://localhost:8000
```

**Comment by eschultink** [comment]
thanks - I confirm that works.  I hadn't noticed the earlier entry in the log; it is referred to as "admin server", not "admin console" - and previously the convention for all built-in interfaces to be hosted under `_ah/`.

And yes, I understand `1` is the supported version; but it's missing a lot of the functionality that the previous gae maven plugin offered, such a way to manage where the local DB and other generated files are stored (`storagePath` in `2`).
