### ISSUE TITLE
appengine:deveserver jetty start with Classnofound exception - java.lang.ClassNotFoundException: com.google.appengine.tools.util.Action

### ISSUE THREAD

**Issue by vijayakumar-psg587** [GoogleCloudPlatform/app-maven-plugin#339]
I am trying to start the appengine devserver to test my changes and I am always endingup with the following exception

> [INFO] GCLOUD: java.lang.ClassNotFoundException: com.google.appengine.tools.util.Action
> [INFO] GCLOUD: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> [INFO] GCLOUD: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> [INFO] GCLOUD: 	at com.google.appengine.tools.development.DevAppServerClassLoader.loadClass(DevAppServerClassLoader.java:108)
> [INFO] GCLOUD: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> [INFO] GCLOUD: 	at java.lang.ClassLoader.defineClass1(Native Method)
> [INFO] GCLOUD: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)

This is my pom.xml -a little too elaborate and too many dependecies but yet to be ironed out. Could you kindly help me in resolving the issue. Could you please help me out resolving the issue

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>XXXX</artifactId>
	<version>0.0.1</version>
	<packaging>war</packaging>

	<name>Adtech-backend services</name>
	<description>Spring boot services to access the data layer API and serve to the adtech UI</description>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<failOnMissingWebXml>false</failOnMissingWebXml>

	</properties>

	<repositories>

		<repository>
			<id>spring-snapshots</id>
			<url>http://repo.spring.io/libs-snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>spring-snapshots</id>
			<url>http://repo.spring.io/libs-snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>


	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.5.RELEASE</version>
	</parent>
	<!-- <repositories> <repository> <snapshots> <enabled>false</enabled> </snapshots> 
		<id>central</id> <url>https://code.bestbuy.com/artifactory/libs-release/</url> 
		</repository> </repositories> <pluginRepositories> <pluginRepository> <snapshots> 
		<enabled>false</enabled> </snapshots> <id>central</id> <url>https://code.bestbuy.com/artifactory/plugins-release/</url> 
		</pluginRepository> </pluginRepositories> -->

	<dependencies>

		<dependency>
			<groupId>javax.inject</groupId>
			<artifactId>javax.inject</artifactId>
			<version>1</version>
		</dependency>

		<!-- <dependency> <groupId>com.google.guava</groupId> <artifactId>guava</artifactId> 
			<version>27.0-jre</version> </dependency> -->

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>

		</dependency>

		<!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind -->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>

		</dependency>

		<!-- https://mvnrepository.com/artifact/com.google.apis/google-api-services-bigquery -->
		<!-- <dependency> <groupId>com.google.apis</groupId> <artifactId>google-api-services-bigquery</artifactId> 
			<version>v2-rev377-1.23.0</version> </dependency> -->

		<!-- https://mvnrepository.com/artifact/com.google.cloud/google-cloud-bigquery -->
		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-bigquery</artifactId>
			<version>1.25.0</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot</artifactId>

		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>

			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
				<!-- <exclusion> <groupId>org.springframework.boot</groupId> <artifactId>spring-boot-starter-logging</artifactId> 
					</exclusion> -->
			</exclusions>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.aspectj/aspectjweaver -->
		<dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjweaver</artifactId>

		</dependency>

		<!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-actuator -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>

		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.9.2</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.9.2</version>
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-bean-validators</artifactId>
			<version>2.9.2</version>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>

			<scope>provided</scope>
		</dependency>

		<!-- https://mvnrepository.com/artifact/com.google.code.gson/gson -->
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>

		</dependency>

		<!-- https://mvnrepository.com/artifact/org.apache.commons/commons-dbcp2 -->
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-dbcp2</artifactId>

		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.google.truth</groupId>
			<artifactId>truth</artifactId>
			<version>0.39</version>
			<scope>test</scope>
		</dependency>

		<!-- https://mvnrepository.com/artifact/com.google.appengine/appengine-api-1.0-sdk -->
		<dependency>
			<groupId>com.google.appengine</groupId>
			<artifactId>appengine-api-1.0-sdk</artifactId>

		</dependency>

		<!-- ≈https://mvnrepository.com/artifact/com.google.appengine/appengine-tools-sdk -->
		<dependency>
			<groupId>com.google.appengine</groupId>
			<artifactId>appengine-tools-sdk</artifactId>
			<version>1.9.63</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.17</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.17</version>
		</dependency>
		
		<dependency>
			<groupId>com.fasterxml.jackson.dataformat</groupId>
			<artifactId>jackson-dataformat-xml</artifactId>
		</dependency>

		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-storage</artifactId>
			<version>1.20.0</version>
		</dependency>
		
		<dependency>
			<groupId>com.google.appengine.tools</groupId>
			<artifactId>appengine-gcs-client</artifactId>
			<version>0.6</version>
		</dependency>
		
		
		<dependency>
			<groupId>org.springframework.security.oauth</groupId>
			<artifactId>spring-security-oauth2</artifactId>
			<version>2.3.3.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security.oauth.boot</groupId>
			<artifactId>spring-security-oauth2-autoconfigure</artifactId>
			
		</dependency>
		<!-- <dependency> <groupId>org.springframework.security</groupId> <artifactId>spring-security-config</artifactId> 
			<version>5.0.4.RELEASE</version> </dependency> -->
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-web</artifactId>

		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-core</artifactId>

		</dependency>

		<!-- https://mvnrepository.com/artifact/org.apache.commons/commons-lang3 -->
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>

		</dependency>

		<!-- https://mvnrepository.com/artifact/org.json/json -->
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20180130</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.googlecode.json-simple/json-simple -->
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>

		</dependency>

		<!-- https://mvnrepository.com/artifact/com.google.cloud/google-cloud-logging-logback -->
		<!-- <dependency> <groupId>com.google.cloud</groupId> <artifactId>google-cloud-logging-logback</artifactId> 
			<version>0.55.1-alpha</version> </dependency> -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jul-to-slf4j</artifactId>

			<scope>provided</scope>

		</dependency>
		<!-- https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt -->
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt</artifactId>
			<version>0.6.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.auth0/java-jwt -->
		<dependency>
			<groupId>com.auth0</groupId>
			<artifactId>java-jwt</artifactId>
			<version>3.4.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-jsr310 -->
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jsr310</artifactId>

		</dependency>
		<!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-jdk8 -->
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jdk8</artifactId>

		</dependency>
		<!-- https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api -->
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>

		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>

		</dependency>

		<!-- https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-jcl -->
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-jcl</artifactId>

		</dependency>

		<!-- IMP + THIS dependency is added to remove the warning that appears 
			while using @ConfigurationProperties -->

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
	</dependencies>
	
	<build>
		<plugins>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<configuration>
					<forkMode>always</forkMode>
					<!--<environmentVariables>
						<LCP>QA</LCP>
					</environmentVariables>-->
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<configuration>
					<packagingExcludes>WEB-INF/lib/websocket-*.jar</packagingExcludes>
				</configuration>
			</plugin>


			<!-- <plugin> <groupId>org.apache.maven.plugins</groupId> <artifactId>maven-compiler-plugin</artifactId> 
				<version>3.7.0</version> <configuration> <source>1.8</source> <target>1.8</target> 
				</configuration> <dependencies> <dependency> <groupId>org.ow2.asm</groupId> 
				<artifactId>asm</artifactId> <version>6.0</version> Use newer version of 
				ASM </dependency> </dependencies> </plugin> -->

			<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>appengine-maven-plugin</artifactId>
				<version>2.0.0-rc2</version>
				<configuration>
					<deploy.projectId>GCLOUD_CONFIG</deploy.projectId>
					<deploy.version>v04</deploy.version>
					<port>8181</port>
					<address>0.0.0.0</address>
					<environment>
						<name>spring.profiles.active</name>
						<value>QA</value>
					</environment>
					<!-- <cloudSdkHome>/Applications/gcloud-sdk/google-cloud-sdk</cloudSdkHome> -->
					<cloudSdkVersion>220.0.0</cloudSdkVersion>
					<!-- <appId>XXXX</appId> -->
					<!-- <deployables> <param>target/XXXX/WEB-INF/appengine-web.xml</param> 
						</deployables> -->
				</configuration>
			</plugin>

			<!-- To expose the git commid id through /info actuator end point. We 
				need it incase if anything goes wrong with deployment -->

			<plugin>
				<groupId>pl.project13.maven</groupId>
				<artifactId>git-commit-id-plugin</artifactId>
			</plugin>

			
			<plugin>
				<groupId>org.eclipse.jetty</groupId>
				<artifactId>jetty-maven-plugin</artifactId>
				<version>9.4.12.v20180830</version>
				<configuration>
					<webApp>
						<contextPath>/XXXX</contextPath>
					</webApp>
					
				</configuration>
			</plugin>
		</plugins>
		<!-- there is an issue with the jks resources getting filtered out by the 
			spring container by default and that was causing the issue So we better clear 
			that filtering -->
		<resources>
			<resource>
				<directory>src/main/resources</directory>

				<includes>
					<include>application.properties</include>
					
					<include>/**</include>
				</includes>
			</resource>
		</resources>
	</build>
	<profiles>
		<profile>
			<id>DEV</id>
			<activation>
				<activeByDefault>true</activeByDefault>

			</activation>
			<properties>
				<spring.profiles.active>DEV</spring.profiles.active>
			</properties>
		</profile>

		<profile>
			<id>QA</id>
			<activation>
				<activeByDefault>false</activeByDefault>

			</activation>
			<properties>
				<spring.profiles.active>QA</spring.profiles.active>
			</properties>
		</profile>


	</profiles>

</project>
```

**Comment by chanseokoh** [comment]
You said `appengine:deveserver`, so I think you are trying to mix the [App Engine SDK-based Maven plugin](https://cloud.google.com/appengine/docs/standard/java/tools/migrate-maven)  and the [Cloud SDK-based Maven plugin](https://cloud.google.com/appengine/docs/standard/java/tools/using-maven)? Not sure how even `appengine:devappserver` is recognized. The Cloud SDK-based Maven plugin uses `appengine:run`. And I'm not sure if the following dependency is needed.
```xml
		<dependency>
			<groupId>com.google.appengine</groupId>
			<artifactId>appengine-tools-sdk</artifactId>
			<version>1.9.63</version>
		</dependency>
```

**Comment by vijayakumar-psg587** [comment]
@chanseokoh that dependency added previously because I was giving a try with different options. It can be ignored. `appengine:deveserver` is just running the server asynchronously and `appengine:run `is running it synchronoulsy. I will try it in both ways and let you know

**Comment by vijayakumar-psg587** [comment]
@chanseokoh This is the error that I get now, after commenting the unwanted dependency

```
Caused by: 
[INFO] GCLOUD: javax.servlet.ServletException: Not running on Jetty, JSR-356 support unavailable
[INFO] GCLOUD: 	at org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer.onStartup(WebSocketServerContainerInitializer.java:200)
[INFO] GCLOUD: 	at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:140)
[INFO] GCLOUD: 	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:64)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:355)
[INFO] GCLOUD: 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
[INFO] GCLOUD: 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:848)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
[INFO] GCLOUD: 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.Server.start(Server.java:419)
```

**Comment by vijayakumar-psg587** [comment]
@chanseokoh No longer any errors occur. The JSR annoataion not supported error is because of the resources not getting filtered properly and the filtering was disabled by default for the use of https in local. I resolved that in my pom.xml
```

<build>
.....
<resources>
		
			
			<resource>
				<directory>src/main/resources</directory>
				<includes>
					<include>application.properties</include>
					<include>keystore.p12</include>
					<include>/**</include>
				</includes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
				
			</resource>
			
		</resources>
		
		
		
	</build>
```

The only change I made was removing the unwanted dependency and I no longer get the error.
Thanks for ypu help though

**Comment by chanseokoh** [comment]
Thanks for the update!
