### ISSUE TITLE
Plugin asks for installing gcloud Python Extension, but no way to interact

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/app-maven-plugin#43]
On my machine (Linux) without the Python Extension, the plugin will show:

```
[INFO] GCLOUD: This action requires the installation of components: [app-engine-
[INFO] GCLOUD: python]
[INFO] GCLOUD: 
[INFO] GCLOUD: 
[INFO] GCLOUD: Your current Cloud SDK version is: 115.0.0
[INFO] GCLOUD: Installing components from version: 115.0.0
[INFO] GCLOUD: 
[INFO] GCLOUD: +--------------------------------------------------+
[INFO] GCLOUD: |       These components will be installed.        |
[INFO] GCLOUD: +------------------------------+---------+---------+
[INFO] GCLOUD: |             Name             | Version |   Size  |
[INFO] GCLOUD: +------------------------------+---------+---------+
[INFO] GCLOUD: | gcloud app Python Extensions |  1.9.38 | 7.2 MiB |
[INFO] GCLOUD: +------------------------------+---------+---------+
[INFO] GCLOUD: 
[INFO] GCLOUD: For the latest full release notes, please visit:
[INFO] GCLOUD:   https://cloud.google.com/sdk/release_notes
[INFO] GCLOUD: 
```

I was under the impression that the plugin is automatically installing the Python Extension. After waiting for 10 minutes, I decided to cancel it (Ctrl+C), and I get the following log:

```
^C[INFO] GCLOUD: Do you want to continue (Y/n)?  Traceback (most recent call last):
[INFO] GCLOUD:   File "/home/chanseok/google-cloud-sdk/bin/dev_appserver.py", line 35, in <module>
[INFO] GCLOUD:     main()
[INFO] GCLOUD:   File "/home/chanseok/google-cloud-sdk/bin/dev_appserver.py", line 22, in main
[INFO] GCLOUD:     command=__file__)
chanseok@chanseok3:~/workspace/mvn/compat$
```

I think it is good make a clear point (in a doc, etc) that the Python Extension is a pre-requisite.

**Comment by meltsufin** [comment]
Did you run `gcloud components install app-engine-java` prior? I believe it pulls Python Extensions.

**Comment by chanseokoh** [comment]
You're right. This issue is not relevant anymore.
